### ISSUE TITLE
DOMPurify Hooks

### ISSUE THREAD

**Issue by EskelCz** [jill64/svelte-sanitize#426]
Hi, thanks for a great tool.

I've run into an issue I don't know how to solve. I need to allow youtube embeds (iframe, but only from youtube.com), which doesn't seem to be solvable only through DOMPurify options object. I think I need hooks. Is there a way to use them through `svelte-sanitize`?

Thanks

**Comment by jill64** [comment]
Thanks for opening this Issue!

New hook function option with DOMPurify object as argument.
This function will be executed before sanitize.
Please check if this solves your problem.
See [universal-sanitizer README](https://github.com/jill64/universal-sanitizer#readme) for a detailed usage example.
